-- Employee Import SQL for Asset Management System
-- Mapping AMS_ID to emp_name from existing portal
-- Default password: Welcome@123 (bcrypt hash)

SET @default_password = '$2y$12$LN1c5/sVqxE6G8UqN0A1eO3M.qR7tHmCbKZwXjVpNlCaTnPfWZIZK';

INSERT INTO `users` (`ams_id`, `emp_name`, `email_id`, `password`, `role`, `department_id`, `designation`) VALUES
('1410001', 'Dr. N. Anandavalli', 'anandavalli@csir.res.in', @default_password, 'admin', NULL, 'Director'),
('1410040', 'Dr. K. Sathish Kumar', 'sathishkumar@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410042', 'Dr. Pabbisetty Harikrishna', 'harikrishna@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410043', 'Dr. S. Parivallal', 'parivallal@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410044', 'Dr. J. Prabakar', 'prabakar@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410049', 'Dr. S. Bhaskar', 'bhaskar@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410053', 'Dr. Saptarshi Sasmal', 'sasmal@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410051', 'Dr. M.B. Anoop', 'anoop@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410052', 'Dr. A. Ramachandra Murthy', 'murthy@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410050', 'Dr. Voggu Srinivas', 'srinivas@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410056', 'Dr. P. Kamatchi', 'kamatchi@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410055', 'Smt. R. Sreekala', 'sreekala@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410054', 'Shri. Gajjala Remesh Babu', 'remeshbabu@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410057', 'Dr. S. Maheswaran', 'maheswaran@csir.res.in', @default_password, 'supervisor', NULL, 'Chief Scientist'),
('1410058', 'Dr. Rokade Rajendra Pitambar', 'rajendra@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410062', 'Dr. Amar Prakash', 'amarprakash@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410066', 'Dr.(Ms.) Smitha Gopinath', 'smitha@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410061', 'Dr. A. Abraham', 'abraham@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410070', 'Dr. S. Vishnuvardhan', 'vishnuvardhan@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410071', 'Dr. K. Lakshmi', 'lakshmi@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410069', 'Dr. V. Marimuthu', 'marimuthu@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410064', 'Shri. V. Srinivasan', 'vsrinivasan@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410072', 'Dr. R. Balagopal', 'balagopal@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410076', 'Dr. B. Arun Sundaram', 'arunsundaram@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410074', 'Dr. M. Saravanan', 'msaravanan@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410068', 'Dr. P.S. Ambily', 'ambily@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410065', 'Dr. R. Manisekar', 'manisekar@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410080', 'Dr. C. Bharathi Priya', 'bharathipriya@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410081', 'Dr. B.S. Sindu', 'sindu@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410082', 'Dr. Prabhat Ranjan Prem', 'prabhatranjan@csir.res.in', @default_password, 'employee', NULL, 'Senior Principal Scientist'),
('1410067', 'Dr. K. Sivasubramanian', 'sivasubramanian@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410073', 'Dr. P. Prabha', 'prabha@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410075', 'Dr. Srinivasa Babu Ramisetti', 'srinivasababu@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410077', 'Shri. A.K. Farvaze Ahmed', 'farvaze@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410078', 'Dr. A. Kanchana Devi', 'kanchanadevi@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410079', 'Dr. Venkata Rama Rao Guntuka', 'venkataramarao@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410083', 'Dr. A. Cinitha', 'cinitha@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410084', 'Dr. T. Hemalatha', 'hemalatha@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410085', 'Dr. S. Sundar Kumar', 'sundarkumar@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410088', 'Dr. Mohit Verma', 'mohitverma@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410093', 'Dr. M. Keerthana', 'keerthana@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410086', 'Shri. G. Ramesh', 'gramesh@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410087', 'Shri. V. Ramesh Kumar', 'rameshkumar@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410090', 'Dr. M. Saravanan', 'msaravanan2@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410091', 'Shri. Vimal Mohan', 'vimalmohan@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410092', 'Dr. K.N. Lakshmikandhan', 'lakshmikandhan@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410095', 'Dr. M. Surendran', 'surendran@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410089', 'Dr. S.R. Balasubramanian', 'balasubramanian@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410094', 'Dr. Bhashya Vankudothu', 'bhashya@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410097', 'Shri. G.S. Vijaya Bhaskara', 'vijayabhaskara@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410098', 'Dr. J. Prawin', 'prawin@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410099', 'Dr. A. Thirumalaiselvi', 'thirumalaiselvi@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410101', 'Shri. M. Kannusamy', 'kannusamy@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410096', 'Shri. K. Saravana Kumar', 'saravanakumar@csir.res.in', @default_password, 'employee', NULL, 'Principal Scientist'),
('1410100', 'Shri. Abhishek Kumar', 'abhishekkumar@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410102', 'Shri. E. Ashok Kumar', 'ashokkumar@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410107', 'Shri. Jonnalagadda Chintaiah Sunil', 'sunil@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410109', 'Dr. K. Senthil Kumar', 'senthilkumar@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410110', 'Dr. J. Venkatesan', 'venkatesan@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410108', 'Dr. A. Subbulakshmi', 'subbulakshmi@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410104', 'Dr. Nartu Manoj Kumar', 'manojkumar@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410105', 'Smt. N. Ramya', 'ramya@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410106', 'Shri. Nitin Khandelwal', 'nitinkhandelwal@csir.res.in', @default_password, 'employee', NULL, 'Senior Scientist'),
('1410112', 'Shri. Deepak Kumar', 'deepakkumar@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410113', 'Ms. Renuka Darshyamkar', 'renuka@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410114', 'Shri. Allamraju Manikantha Sarath', 'manikantha@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410115', 'Shri. S. Vinoth Kirshnan', 'vinothkirshnan@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410116', 'Ms. G. Nasima', 'nasima@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410117', 'Shri. M. Aravindan', 'aravindan@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410118', 'Dr. M.J. Mahesh', 'mahesh@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410119', 'Shri. Kanishka Bhattacharya', 'kanishka@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410120', 'Shri. Thondamon V', 'thondamon@csir.res.in', @default_password, 'employee', NULL, 'Scientist'),
('1410121', 'Shri. R.D. Sathish Kumar', 'rdsathishkumar@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410123', 'Shri. G. Muthuramalingam', 'muthuramalingam@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410125', 'Shri. G. Jayaraman', 'jayaraman@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410126', 'Shri. M. Kumarappan', 'kumarappan@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410129', 'Smt. Chitra Sankaran', 'chitra@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410150', 'Shri. S. Srinivasan', 'ssrinivasan@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410149', 'Dr. S. Vijayalakshmi', 'vijayalakshmi@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410131', 'Shri. S. Kanniah Sah', 'kanniahsah@csir.res.in', @default_password, 'employee', NULL, 'Principal Technical Officer'),
('1410134', 'Shri. J. Prakashvel', 'prakashvel@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (3)'),
('1410136', 'Shri. S. Harishkumaran', 'harishkumaran@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (3)'),
('1410137', 'Shri. S. Muraleeswaran', 'muraleeswaran@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (3)'),
('1410138', 'Smt. E. Kanmani', 'kanmani@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (2)'),
('1410139', 'Ms. R. Lakshmi Poorna', 'lakshmipoorna@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (2)'),
('1410140', 'Shri. P. Vasudevan', 'vasudevan@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (2)'),
('1410187', 'Shri. R.M. Manikandan', 'rmmanikandan@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (2)'),
('1410141', 'Smt. R. Soniya', 'soniya@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (1)'),
('1410142', 'Shri. M. Vinothkumar', 'mvinothkumar@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (1)'),
('1410143', 'Shri. P. Subbash', 'subbash@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (1)'),
('1410145', 'Shri. G.V. Ananthakrishnan', 'ananth.serc@csir.res.in', @default_password, 'admin', NULL, 'Senior Technical Officer (1)'),
('1410148', 'Shri. G. Lakshmikanth', 'lakshmikanth@csir.res.in', @default_password, 'employee', NULL, 'Senior Technical Officer (1)'),
('1410144', 'Shri. K. Kumaran', 'kumaran@csir.res.in', @default_password, 'employee', NULL, 'Assistant Executive Engineer (Elect.)'),
('1410146', 'Smt. E. Surya', 'surya.serc@csir.res.in', @default_password, 'employee', NULL, 'Technical Officer'),
('1410147', 'Shri. S. Viswanatha Manikandandan', 'viswanatha@csir.res.in', @default_password, 'employee', NULL, 'Technical Officer'),
('1410151', 'Shri. Sadhiq Shaik', 'sadhiq@csir.res.in', @default_password, 'employee', NULL, 'Technical Assistant'),
('1410152', 'Shri. M. Elamaran', 'elamaran@csir.res.in', @default_password, 'employee', NULL, 'Technical Assistant'),
('1410154', 'Shri. D. Deivaraj', 'deivaraj@csir.res.in', @default_password, 'employee', NULL, 'Senior Technician (3)'),
('1410162', 'Shri. G. Ponnan', 'ponnan@csir.res.in', @default_password, 'employee', NULL, 'Senior Technician (3)'),
('1410157', 'Shri. S. Srinivasan', 'ssrinivasan2@csir.res.in', @default_password, 'employee', NULL, 'Senior Technician (3)'),
('1410159', 'Smt. J. Rajalakshmi', 'rajalakshmi@csir.res.in', @default_password, 'employee', NULL, 'Senior Technician (2)'),
('1410160', 'Shri. N. Baskaran', 'baskaran@csir.res.in', @default_password, 'employee', NULL, 'Senior Technician (2)'),
('1410161', 'Shri. V. Krishnan', 'vkrishnan@csir.res.in', @default_password, 'employee', NULL, 'Senior Technician (2)'),
('1410163', 'Shri. R. Rajesh', 'rrajesh@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410164', 'Shri. G. Poovendan', 'poovendan@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410165', 'Shri. S. Bala Murugan', 'balamurugan@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410166', 'Shri. K. Srinivasan', 'ksrinivasan@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410167', 'Shri. T. Sathish Kumar', 'tsathishkumar@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410168', 'Smt. S. Vimala', 'vimala@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410169', 'Shri. A. Karunakaran', 'karunakaran@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410170', 'Shri. S. Muthuraj', 'muthuraj@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410171', 'Smt. K. Savitha', 'savitha@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410172', 'Shri. M. Karunamoorthi', 'karunamoorthi@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410173', 'Shri. N. Syed Ibrahim', 'syedibrahim@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410174', 'Shri. V. Mahendran', 'mahendran@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410175', 'Shri. S. Balakrishnan', 'sbalakrishnan@csir.res.in', @default_password, 'employee', NULL, 'Technician (2)'),
('1410177', 'Shri. S. Eswaran', 'eswaran@csir.res.in', @default_password, 'employee', NULL, 'Lab Assistant'),
('1410002', 'Shri. Lokanath Patnayak', 'lokanath@csir.res.in', @default_password, 'employee', NULL, 'Administrative Officer'),
('1410004', 'Ms. Sudha Nair', 'sudhanair@csir.res.in', @default_password, 'employee', NULL, 'Section Officer (G)'),
('1410005', 'Dr. N. Sudhakar', 'sudhakar@csir.res.in', @default_password, 'employee', NULL, 'Section Officer (G)'),
('1410008', 'Smt. S.P. Kalaivani', 'kalaivani@csir.res.in', @default_password, 'employee', NULL, 'Section Officer (G)'),
('1410202', 'Smt. N. Geetha', 'geetha@csir.res.in', @default_password, 'employee', NULL, 'Section Officer (G)'),
('1410009', 'Smt. M. Vanijayaleela', 'vanijayaleela@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (Gen)'),
('1410232', 'Smt. N. Hemamalini', 'hemamalini@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (Gen)'),
('1410012', 'Smt. M.A. Kamsar Chinnappan', 'kamsar@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (Gen)'),
('1410204', 'Ms. Megha', 'megha@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (Gen)'),
('1410205', 'Ms. Monu', 'monu@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (Gen)'),
('1410207', 'Shri. Jeyaram R', 'jeyaram@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (Gen)'),
('1410212', 'Ms. Paviya P', 'paviya@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410215', 'Smt. Gayathri Devi K', 'gayathridevi@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410219', 'Smt. Rajeshwari S', 'rajeshwari@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410220', 'Shri. Mohansurya S', 'mohansurya@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410234', 'Smt. V.D. Jhansirani', 'jhansirani@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410221', 'Ms. R. Sreeranjini', 'sreeranjini@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410227', 'Shri. Ganta Praveen', 'praveen@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410222', 'Shri. Pon Ramalinga Vel S', 'ramalingavel@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410229', 'Shri. Mukesh RA', 'mukesh@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410231', 'Shri. A.V. Rakesh', 'rakesh@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (Gen)'),
('1410233', 'Shri. T. Karthikai Kannan', 'karthikaikannan@csir.res.in', @default_password, 'employee', NULL, 'Controller of Finance & Accounts'),
('1410208', 'Ms. Sonu', 'sonu@csir.res.in', @default_password, 'employee', NULL, 'Section Officer (F&A)'),
('1410209', 'Smt. Poonam Chahal', 'poonam@csir.res.in', @default_password, 'employee', NULL, 'Section Officer (F&A)'),
('1410014', 'Smt. K. Uma Maheswari', 'umamaheswari@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (F&A)'),
('1410015', 'Smt. M. Thulasi', 'thulasi@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (F&A)'),
('1410206', 'Shri. Vishnu Prasath S', 'vishnuprasath@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (F&A)'),
('1410216', 'Smt. Manthra S', 'manthra@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (F&A)'),
('1410230', 'Ms. Sharon Nivedha J R', 'sharonnivedha@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (F&A)'),
('1410210', 'Shri. E. Mahesh Kumar', 'emaheshkumar@csir.res.in', @default_password, 'supervisor', NULL, 'Controller of Stores & Purchase'),
('1410186', 'Shri. N. Suresh', 'nsuresh@csir.res.in', @default_password, 'employee', NULL, 'Section Officer (S&P)'),
('1410019', 'Shri. M. Palanisamy', 'palanisamy@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (S&P)'),
('1410020', 'Shri. S. Kannappan', 'kannappan@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (S&P)'),
('1410022', 'Shri. C. Rajaji', 'rajaji@csir.res.in', @default_password, 'employee', NULL, 'Assistant Section Officer (S&P)'),
('1410023', 'Shri. Sai Sudheer Amba', 'saisudheer@csir.res.in', @default_password, 'employee', NULL, 'Senior Secretariat Assistant (S&P)'),
('1410213', 'Shri. M. Barani Dharan', 'baranidharan@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (S&P)'),
('1410214', 'Shri. Karthigeyan K', 'karthigeyan@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (S&P)'),
('1410223', 'Shri. Peddipaga Teja', 'teja@csir.res.in', @default_password, 'employee', NULL, 'Junior Secretariat Assistant (S&P)'),
('1410024', 'Shri. B. Ravikumar', 'ravikumar@csir.res.in', @default_password, 'employee', NULL, 'Principal Private Secretary'),
('1410025', 'Smt. K. Venkateswari', 'venkateswari@csir.res.in', @default_password, 'employee', NULL, 'Private Secretary'),
('1410026', 'Smt. S. Jagadhaprabha', 'jagadhaprabha@csir.res.in', @default_password, 'employee', NULL, 'Private Secretary'),
('1410028', 'Smt. M. Vijayalakshmi', 'mvijayalakshmi@csir.res.in', @default_password, 'employee', NULL, 'Private Secretary'),
('1410030', 'Smt. S. Shanthi', 'shanthi@csir.res.in', @default_password, 'employee', NULL, 'Senior Stenographer'),
('1410031', 'Shri. S.M. Yuvaraj', 'yuvaraj@csir.res.in', @default_password, 'employee', NULL, 'Senior Stenographer'),
('1410224', 'Ms. Akshaya V', 'akshaya@csir.res.in', @default_password, 'employee', NULL, 'Junior Stenographer'),
('1410228', 'Ms. Swetha G M', 'swetha@csir.res.in', @default_password, 'employee', NULL, 'Junior Stenographer'),
('1410203', 'Dr. Asha G. Nair', 'ashanair@csir.res.in', @default_password, 'employee', NULL, 'Hindi Officer'),
('1410034', 'Shri. K. Jagannathan', 'jagannathan@csir.res.in', @default_password, 'employee', NULL, 'Driver II (4)'),
('1410037', 'Shri. D. John', 'john@csir.res.in', @default_password, 'employee', NULL, 'Driver II (3)'),
('1410225', 'Shri. Bhukya Ramki Nayak', 'ramkinayak@csir.res.in', @default_password, 'employee', NULL, 'Driver'),
('1410226', 'Shri. Saravanan K', 'ksaravanan@csir.res.in', @default_password, 'employee', NULL, 'Driver'),
('1410178', 'Smt. B. Reeta Sangeetha', 'reetasangeetha@csir.res.in', @default_password, 'employee', NULL, 'MTS')
ON DUPLICATE KEY UPDATE emp_name = VALUES(emp_name), designation = VALUES(designation);

-- Total: 164 employees imported
